"use client";

/**
 * Data layer for the Reconstructions explorer.
 *
 * Assets live in `public/reconstructions/` (generated by
 * `pruebas/scripts/build-recon-web-data.ts` from the CubeRoot + reco.nz
 * crawls):
 *   - index.json               → list metadata for every solve
 *   - data/chunk-XXX.json      → full records (scramble, phases, text, stats,
 *                                baked recognition)
 *
 * Both are fetched lazily and cached in module scope. The recognition data
 * per phase (case number, slot, verified) was baked at build time.
 */
import type { Solve } from "@/types";
import type { CubeMoveEvent, SolveMetrics } from "@cubeforge/types";
import { expandWideMoves } from "@cubeforge/math-core";

// ─── Types (mirror of the build script output) ──────────────────────────────

export type ReconSource = "cuberoot" | "reconz";
export type ReconMethodGroup = "CFOP" | "Roux" | "Other";

export interface ReconIndexEntry {
  key: string;
  source: ReconSource;
  id: number;
  solver: string;
  time: number; // seconds
  date: string | null;
  competition: string;
  method: string;
  methodGroup: ReconMethodGroup;
  /** Normalized puzzle label ("3x3", "2x2", "pyraminx", …). */
  puzzle: string;
  stm: number | null;
  tps: number | null;
  tags: string[];
  url: string | null;
}

export interface ReconPhase {
  label: string;
  moves: string;
  moveCount: number;
  recog?: {
    caseNumber: string | null;
    slot: "FR" | "FL" | "BL" | "BR" | null;
    verified: boolean;
  } | null;
}

export interface ReconFullRecord extends ReconIndexEntry {
  scramble: string;
  text: string;
  phases: ReconPhase[];
  stats: {
    crossStm?: number | null;
    f2l?: number | null;
    ll?: number | null;
    yRot?: number | null;
    regrip?: number | null;
    freePair?: number | null;
    sMove?: number | null;
    crossColor?: string | null;
    videoUrl?: string | null;
    recordAverage?: string | null;
  };
  recognition: {
    finalSolved: boolean;
    inspection: string;
    crossVerified: boolean;
  };
}

interface ReconIndexFile {
  version: number;
  count: number;
  chunkSize: number;
  solves: ReconIndexEntry[];
}

// ─── Fetch + cache ──────────────────────────────────────────────────────────

let indexPromise: Promise<ReconIndexFile> | null = null;
const recordCache = new Map<string, Promise<ReconFullRecord | null>>();

function loadIndex(): Promise<ReconIndexFile> {
  indexPromise ??= fetch(`${import.meta.env.BASE_URL}reconstructions/index.json`).then(
    (r) => {
      if (!r.ok) throw new Error(`reconstructions index: HTTP ${r.status}`);
      return r.json() as Promise<ReconIndexFile>;
    },
  );
  return indexPromise;
}

/** All list entries (memoised). Throws on fetch failure. */
export function useReconIndex(): Promise<ReconIndexEntry[]> {
  return loadIndex().then((f) => f.solves);
}

/** Load the full record for one reconstruction key (cached). */
export function fetchReconRecord(key: string): Promise<ReconFullRecord | null> {
  const cached = recordCache.get(key);
  if (cached) return cached;

  const promise = (async () => {
    const index = await loadIndex();
    const rank = index.solves.findIndex((e) => e.key === key);
    if (rank < 0) return null;
    const chunk = Math.floor(rank / index.chunkSize);
    const file = `${import.meta.env.BASE_URL}reconstructions/data/chunk-${String(chunk).padStart(3, "0")}.json`;
    const res = await fetch(file);
    if (!res.ok) throw new Error(`reconstructions chunk ${chunk}: HTTP ${res.status}`);
    const data = (await res.json()) as { solves: ReconFullRecord[] };
    const record = data.solves.find((s) => s.key === key) ?? null;
    if (record) normalizeReconSeparators(record);
    return record;
  })();

  recordCache.set(key, promise);
  return promise;
}

// ─── Replay helper ──────────────────────────────────────────────────────────

const ROTATION_RE = /^[xyz]'?2?$/;
const SLICE_RE = /^[MSE]'?2?$/;

/**
 * CubeRoot / Quest write separators between moves (↓ ↑ · .) to mark regrips
 * / cancellations. The baked JSON kept them inside `phase.moves`, which breaks
 * both the Steps table render and the replay. We normalize phase moves on load
 * (display + replay) but leave the raw `text` untouched for copy.
 */
const SEPARATOR_RE = /[↓↑·.]/g;

function normalizeReconSeparators(record: ReconFullRecord): void {
  for (const phase of record.phases) {
    const cleaned = phase.moves.replace(SEPARATOR_RE, " ").replace(/\s+/g, " ").trim();
    phase.moves = cleaned;
    phase.moveCount = cleaned ? cleaned.split(/\s+/).length : 0;
  }
}

/**
 * Turn a notation string into CubeMoveEvents for the ReplayEngine.
 *
 * Wide moves are expanded to their face turn (r → R) and slice/rotation
 * tokens are dropped: the ReplayEngine can only animate outer-face turns
 * (FACE_ROTATION_MAP has no M/S/E/x/y/z). The turn SEQUENCE is preserved —
 * rotations are visual-only and do not affect the solution. Events are
 * spaced at a fixed 550ms so the replay timeline is proportional to moves.
 */
export function notationToReplayMoves(notation: string, start = 0): CubeMoveEvent[] {
  const tokens = expandWideMoves(notation.trim().split(/[\s↓↑·.]+/).filter(Boolean));
  const events: CubeMoveEvent[] = [];
  let ts = start;
  for (const token of tokens) {
    if (ROTATION_RE.test(token) || SLICE_RE.test(token)) continue;
    const face = token[0] as CubeMoveEvent["face"];
    const suffix = token.slice(1);
    const direction = suffix === "2" ? 2 : suffix === "'" ? -1 : 1;
    events.push({
      face,
      direction,
      cubeTimestamp: ts,
      hostTimestamp: ts,
    });
    ts += 550;
  }
  return events;
}

/**
 * Adapt a reconstruction record to the `Solve` shape the ReplaySection
 * consumes (replay canvas + transport + live phase indicator).
 */
export function reconToSolve(record: ReconFullRecord): Solve {
  const allMoves = record.phases.map((p) => p.moves).join(" ");
  const moves = notationToReplayMoves(allMoves);

  const phases: SolveMetrics["phases"] = record.phases.map((p) => ({
    phaseName: p.label,
    durationMs: 0,
    moveCount: p.moveCount,
    tps: 0,
    pauseCount: 0,
    pauseTimeMs: 0,
  }));

  const dateTs = record.date ? Date.parse(record.date) : 0;

  return {
    id: record.key,
    time: Math.round(record.time * 1000),
    penalty: "none",
    scramble: record.scramble,
    timestamp: Number.isFinite(dateTs) ? dateTs : 0,
    method: record.method as Solve["method"],
    source: "manual",
    moves,
    // So 2×2 reconstructions replay on a 2×2 cube (not a 3×3).
    puzzleType:
      record.puzzle === "2x2"
        ? "2x2x2"
        : record.puzzle === "3x3"
          ? "3x3x3"
          : undefined,
    analysis: { phases } as unknown as SolveMetrics,
  };
}
