"use client";

/**
 * Data layer for the Reconstructions explorer.
 *
 * Assets live in `public/reconstructions/` (generated by
 * `pruebas/scripts/build-recon-web-data.ts` from the CubeRoot + reco.nz
 * crawls):
 *   - index.json               → list metadata for every solve
 *   - data/chunk-XXX.json      → full records (scramble, phases, text, stats,
 *                                baked recognition)
 *
 * Both are fetched lazily and cached in module scope. The recognition data
 * per phase (case number, slot, verified) was baked at build time.
 */
import type { Solve } from "@/types";
import type {
  CubeMoveEvent,
  OrientationTimeline,
  SolveMetrics,
} from "@cubeforge/types";
import {
  conjugatePhaseStream,
  isRotation,
  tokenize,
} from "@cubeforge/math-core";

// ─── Types (mirror of the build script output) ──────────────────────────────

export type ReconSource = "cuberoot" | "reconz";
export type ReconMethodGroup = "CFOP" | "Roux" | "Other";

export interface ReconIndexEntry {
  key: string;
  source: ReconSource;
  id: number;
  solver: string;
  time: number; // seconds
  date: string | null;
  competition: string;
  method: string;
  methodGroup: ReconMethodGroup;
  /** Normalized puzzle label ("3x3", "2x2", "pyraminx", …). */
  puzzle: string;
  stm: number | null;
  tps: number | null;
  tags: string[];
  url: string | null;
}

export interface ReconPhase {
  label: string;
  /** Display notation — a DIRECT parse of the raw phase (wide moves, slices
   *  and rotations keep their written form, e.g. `r'`, `x'`). This is what
   *  the Steps table shows, exactly like the reconstructor wrote it. */
  moves: string;
  /** Raw token count of the display notation (each written move = 1). */
  moveCount: number;
  /** Conjugated cube-frame moves for the 3D replay (rotations folded; wide
   *  moves decomposed into face + slice, BOTH kept — the engine animates
   *  M/E/S as middle-layer turns). Computed at load by `normalizeReconMoves`;
   *  absent in baked data. */
  replayMoves?: string;
  /** Length of `replayMoves` — matches the replay event array 1:1. */
  replayMoveCount?: number;
  /** Per-event `true` when the raw reconstruction wrote a WIDE move
   *  (r/l/u/d/f/b) for that replay event. Parallel to the `replayMoves`
   *  tokens; the engine rotates the outer AND middle layer together for
   *  those. Absent in baked data (computed at load). */
  replayWide?: boolean[];
  /** Per-event display override — the written wide token (e.g. "r'") for
   *  wide events, `null` otherwise. Parallel to `replayMoves`. */
  replayDisplay?: (string | null)[];
  recog?: {
    caseNumber: string | null;
    slot: "FR" | "FL" | "BL" | "BR" | null;
    verified: boolean;
  } | null;
}

export interface ReconFullRecord extends ReconIndexEntry {
  scramble: string;
  text: string;
  phases: ReconPhase[];
  /** Reconstructor credits (reco.nz: Brest/Stewy/…, CubeRoot: reconer). */
  reconstructor?: string | null;
  /** Single-solve record tag (WR/NR/PR…) when the source reports one. */
  record?: string | null;
  /** CubeRoot: round average for the solve (seconds). */
  average?: number | null;
  /** CubeRoot: solve number within the round (1..5). */
  solveNum?: number | null;
  /** CubeRoot: cube model used. */
  cube?: string | null;
  /** CubeRoot: ISO country code. */
  country?: string | null;
  /** CubeRoot: official flag ("wca"…). */
  official?: string | null;
  /** CubeRoot: WCA competition id. */
  compWcaId?: string | null;
  stats: {
    crossStm?: number | null;
    f2l?: number | null;
    ll?: number | null;
    yRot?: number | null;
    regrip?: number | null;
    freePair?: number | null;
    sMove?: number | null;
    crossColor?: string | null;
    videoUrl?: string | null;
    recordAverage?: string | null;
  };
  recognition: {
    finalSolved: boolean;
    inspection: string;
    crossVerified: boolean;
  };
  /** Whole-cube rotations (x/y/z) in the stream, computed at load — the 3D
   *  engine cannot animate them, so they are folded into the conjugated
   *  moves and never shown as replay steps (same as the smartcube path). */
  rotationCount: number;
  /** Synthetic orientation keyframes ([eventIndex, orientationIndex]) so the
   *  3D replay rotates the cube to the solver's perspective like the
   *  smartcube path (empty when the record has no rotations).
   *
   *  IMPORTANT: indices are in EVENT space — the same space as the replay
   *  `moves` array, which includes the slice half of wide moves. Do NOT
   *  index this against the face-only display moves of `p.moves`. */
  orientationTimeline: OrientationTimeline;
}

interface ReconIndexFile {
  version: number;
  count: number;
  chunkSize: number;
  solves: ReconIndexEntry[];
}

// ─── Fetch + cache ──────────────────────────────────────────────────────────

let indexPromise: Promise<ReconIndexFile> | null = null;
const recordCache = new Map<string, Promise<ReconFullRecord | null>>();

function loadIndex(): Promise<ReconIndexFile> {
  indexPromise ??= fetch(`${import.meta.env.BASE_URL}reconstructions/index.json`).then(
    (r) => {
      if (!r.ok) throw new Error(`reconstructions index: HTTP ${r.status}`);
      return r.json() as Promise<ReconIndexFile>;
    },
  );
  return indexPromise;
}

/** All list entries (memoised). Throws on fetch failure. */
export function fetchReconIndex(): Promise<ReconIndexEntry[]> {
  return loadIndex().then((f) => f.solves);
}

/** Load the full record for one reconstruction key (cached). */
export function fetchReconRecord(key: string): Promise<ReconFullRecord | null> {
  const cached = recordCache.get(key);
  if (cached) return cached;

  const promise = (async () => {
    const index = await loadIndex();
    const rank = index.solves.findIndex((e) => e.key === key);
    if (rank < 0) return null;
    const chunk = Math.floor(rank / index.chunkSize);
    const file = `${import.meta.env.BASE_URL}reconstructions/data/chunk-${String(chunk).padStart(3, "0")}.json`;
    const res = await fetch(file);
    if (!res.ok) throw new Error(`reconstructions chunk ${chunk}: HTTP ${res.status}`);
    const data = (await res.json()) as { solves: ReconFullRecord[] };
    const record = data.solves.find((s) => s.key === key) ?? null;
    if (record) normalizeReconMoves(record);
    return record;
  })();

  recordCache.set(key, promise);
  return promise;
}

// ─── Replay helper ──────────────────────────────────────────────────────────

/**
 * Suffix-aware move forms — CubeRoot writes `U2'` and `R2'` (three chars),
 * which `expandWideMoves` normalizes to `U2`/`R2` before conjugation. Every
 * regex here accepts the `2'` form so RAW display tokens and their expanded
 * counterparts count identically as face turns.
 */
const SUFFIX = "(?:2'|2|')?";

/** Valid outer-face turns — the tokens `conjugatePhaseStream` counts when
 *  emitting orientation keyframes (mirror of its `isSliceToken`). */
const FACE_MOVE_RE = new RegExp(`^[URFDLB]${SUFFIX}$`);

/** Valid animatable moves — outer faces PLUS slices plus lowercase wides.
 *  The 3D engine animates M/E/S as middle-layer turns (FACE_ROTATION_MAP)
 *  and lowercase wides as two-layer turns. */
const ANIMATABLE_MOVE_RE = new RegExp(`^[URFDLBMESrludfb]${SUFFIX}$`);

/** Wide moves as written by the solver (r, l', u2, Rw, Uw2, …). A wide is a
 *  SINGLE replay event that rotates the outer layer AND the middle layer
 *  together; the display keeps the written token verbatim. */
const WIDE_MOVE_RE = new RegExp(`^([rludfb]${SUFFIX}|[RLUDFB]w${SUFFIX})$`);

/**
 * Re-index the synthetic orientation timeline from FACE-move space to RAW
 * EVENT space. `conjugatePhaseStream` counts only outer-face turns (their
 * `isSliceToken` counter) when emitting keyframes — a written wide `r'`
 * counts as ONE face turn (its expanded face half), a slice `M'` counts as
 * ZERO. In the raw replay the event array holds every written token except
 * rotations (wides stay whole), so the mapping is:
 *
 *   face turn k → the raw event index of the k-th face-or-wide token
 *
 * Slices and wides therefore never cause an off-by-N drift between the
 * timeline's face space and the replay's event space.
 */
function reindexTimelineToRawEventSpace(
  timeline: OrientationTimeline,
  displayTokensPerPhase: string[][],
): OrientationTimeline {
  if (timeline.length === 0) return timeline;
  const faceToEvent: number[] = [];
  let faceIdx = 0;
  let eventIdx = 0;
  for (const phase of displayTokensPerPhase) {
    for (const tok of phase) {
      if (isRotation(tok)) continue;
      // A wide's outer layer IS the counted face turn; a slice is not.
      if (WIDE_MOVE_RE.test(tok) || FACE_MOVE_RE.test(tok)) faceToEvent[faceIdx++] = eventIdx;
      eventIdx++;
    }
  }
  return timeline.map(([moveIndex, orient]) => [
    faceToEvent[moveIndex] ?? moveIndex,
    orient,
  ]);
}

/**
 * Normalize a record's phase moves at load time, once.
 *
 * TWO representations are kept apart:
 *
 * 1. **Display (`p.moves` / `p.moveCount`)** — a DIRECT parse of the raw
 *    phase: `tokenize(..., { expandWide: false })` splits CubeRoot's glued
 *    tokens ("U'D" → U' + D), Unicode primes and the ↓ ↑ · . separators, but
 *    keeps wide moves (`r'`) and rotations (`x'`) as written. The Steps
 *    table shows exactly what the reconstructor wrote.
 * 2. **Replay (`p.replayMoves` / `p.replayMoveCount`)** — the SAME written
 *    tokens minus rotations, one event per token (wides stay whole — the 3D
 *    engine rotates outer + middle layer TOGETHER). These are SOLVER-frame
 *    moves: the 3D replay rotates the cube root to the solver's grip
 *    (inspection + mid-solve rotations from `orientationTimeline`) while the
 *    moves play in the cube's own frame — exactly like the smartcube path,
 *    so the cube ends solved in the solver's perspective.
 *
 * `conjugatePhaseStream` is still used to derive the rotation count and the
 * synthetic orientation timeline (its conjugated stream itself is NOT used
 * for replay anymore — the root rotation replaces conjugation visually).
 *
 * The raw `text` is left untouched for copy.
 */
function normalizeReconMoves(record: ReconFullRecord): void {
  const { rotationCount, orientationTimeline } = conjugatePhaseStream(
    record.phases.map((p) => tokenize(p.moves)),
  );
  record.rotationCount = rotationCount;

  const displayTokensPerPhase: string[][] = [];
  record.phases.forEach((p) => {
    // Display: direct parse of the raw phase — no wide expansion, so the
    // written notation (r', U2', x') survives for the Steps table.
    const displayTokens = tokenize(p.moves, { expandWide: false });
    p.moves = displayTokens.join(" ");
    p.moveCount = displayTokens.length;

    // RAW replay events: every written token except rotations, one event per
    // token. Wides stay whole (single two-layer event, written token kept as
    // the display override); slices (M/E/S) are real middle-layer turns;
    // rotations live on the orientation timeline (0 events).
    const events: { token: string; wide: boolean; display: string | null }[] = [];
    for (const dt of displayTokens) {
      if (isRotation(dt)) continue; // grip rotation → orientation keyframe
      const isWide = WIDE_MOVE_RE.test(dt);
      events.push({ token: dt, wide: isWide, display: isWide ? dt : null });
    }
    displayTokensPerPhase.push(displayTokens);
    p.replayMoves = events.map((e) => e.token).join(" ");
    p.replayMoveCount = events.length;
    p.replayWide = events.map((e) => e.wide);
    p.replayDisplay = events.map((e) => e.display);
  });

  // The orientation timeline is emitted in FACE-move space; re-index every
  // keyframe to raw-event space so the 3D replay grips the solver's frame at
  // the right event (inspection → keyframe at event 0).
  record.orientationTimeline = reindexTimelineToRawEventSpace(
    orientationTimeline,
    displayTokensPerPhase,
  );
  // Scrambles can carry CubeRoot separators too ("↓F2") — tokenize them so
  // the ReplayEngine's applyInitialScramble gets clean elementary tokens.
  record.scramble = tokenize(record.scramble)
    .filter((t) => ANIMATABLE_MOVE_RE.test(t))
    .join(" ");
}

/**
 * Turn a RAW solver-frame notation string into CubeMoveEvents for the
 * ReplayEngine. The tokens are the solver's own letters (wide moves kept
 * whole — NOT conjugated): the 3D replay rotates the cube root to the
 * solver's grip (orientation timeline) while the moves play in the cube's
 * own frame, exactly like the smartcube path.
 *
 * `options.wide`/`options.display` (parallel to the tokens) mark which
 * events were WIDE moves as written: those get `wide: true` (the engine
 * rotates outer + middle layer TOGETHER) and a `displayNotation` override so
 * the UI shows "r'" instead of "R".
 *
 * Normalizations applied here (display tokens keep the written form for the
 * Steps table, events need the animatable form):
 *   - `U2'` / `R2'` → direction 2 (a 180° turn, `2'` ≡ `2`);
 *   - lowercase wides `r'` → face `R` + `wide: true` (FACE_ROTATION_MAP is
 *     keyed by uppercase faces; the wide flag restores the written token).
 *
 * Events are spaced at a fixed 550ms so the replay timeline is proportional
 * to moves.
 */
export function notationToReplayMoves(
  notation: string,
  options?: { wide?: boolean[]; display?: (string | null)[]; start?: number },
): CubeMoveEvent[] {
  const tokens = tokenize(notation, { expandWide: false });
  const events: CubeMoveEvent[] = [];
  let ts = options?.start ?? 0;
  const wide = options?.wide;
  const display = options?.display;
  for (let i = 0; i < tokens.length; i++) {
    const token = tokens[i];
    if (!ANIMATABLE_MOVE_RE.test(token)) continue; // garbage can't animate
    const isWide = wide?.[i] === true;
    // Wides are written lowercase (r'); the engine's FACE_ROTATION_MAP is
    // keyed uppercase — normalize while keeping the wide flag + token.
    const face = (isWide ? token[0].toUpperCase() : token[0]) as CubeMoveEvent["face"];
    const rawSuffix = token.slice(1);
    const suffix = rawSuffix === "2'" ? "2" : rawSuffix; // U2' ≡ U2
    const direction = suffix === "2" ? 2 : suffix === "'" ? -1 : 1;
    events.push({
      face,
      direction,
      wide: isWide,
      displayNotation: isWide ? display?.[i] ?? face + suffix : undefined,
      cubeTimestamp: ts,
      hostTimestamp: ts,
    });
    ts += 550;
  }
  return events;
}

/**
 * Adapt a reconstruction record to the `Solve` shape the ReplaySection
 * consumes (replay canvas + transport + live phase indicator).
 */
export function reconToSolve(record: ReconFullRecord): Solve {
  // Replay path uses the RAW SOLVER-FRAME moves (replayMoves = written tokens
  // minus rotations), NOT a conjugated stream — the 3D engine rotates the
  // cube root to the solver's grip (inspection + mid-solve rotations from
  // `orientationTimeline`) while the moves play in the cube's own frame, so
  // the cube ends solved IN THE SOLVER'S PERSPECTIVE. Wide marks + display
  // overrides travel alongside so a written `r'` replays as ONE two-layer
  // move showing "r'".
  const allTokens: string[] = [];
  const allWide: boolean[] = [];
  const allDisplay: (string | null)[] = [];
  for (const p of record.phases) {
    const tokens = (p.replayMoves ?? p.moves).split(" ").filter(Boolean);
    allTokens.push(...tokens);
    allWide.push(...(p.replayWide ?? tokens.map(() => false)));
    allDisplay.push(...(p.replayDisplay ?? tokens.map(() => null)));
  }
  const moves = notationToReplayMoves(allTokens.join(" "), {
    wide: allWide,
    display: allDisplay,
  });

  // The synthetic orientation timeline rotates the 3D cube to the solver's
  // perspective during replay (same as the smartcube path), so the displayed
  // notation matches what the reconstructor wrote instead of the physical
  // cube-frame letters.
  const orientationTimeline =
    record.orientationTimeline && record.orientationTimeline.length > 0
      ? record.orientationTimeline
      : undefined;

  // p.replayMoveCount is the CONJUGATED face-move count (normalizeReconMoves),
  // so it matches the replay `moves` array below exactly — rotations are
  // folded into the moves and never counted, same as the smartcube path.
  const phases: SolveMetrics["phases"] = record.phases.map((p) => ({
    phaseName: p.label,
    durationMs: 0,
    moveCount: p.replayMoveCount ?? p.moveCount,
    tps: 0,
    pauseCount: 0,
    pauseTimeMs: 0,
  }));

  const dateTs = record.date ? Date.parse(record.date) : 0;

  return {
    id: record.key,
    time: Math.round(record.time * 1000),
    penalty: "none",
    scramble: record.scramble,
    timestamp: Number.isFinite(dateTs) ? dateTs : 0,
    method: record.method as Solve["method"],
    source: "manual",
    moves,
    orientationTimeline,
    // The replay moves are RAW SOLVER-FRAME letters (rotations NOT folded in)
    // — `replayMovesConjugated: false` tells the replay section that the
    // orientation timeline MUST rotate the cube root (the solver's grip:
    // inspection pre-roll + mid-solve keyframes), and that the displayed
    // notation is already the solver's own letters (no remapping needed).
    replayMovesConjugated: false,
    // So 2×2 reconstructions replay on a 2×2 cube (not a 3×3).
    puzzleType:
      record.puzzle === "2x2"
        ? "2x2x2"
        : record.puzzle === "3x3"
          ? "3x3x3"
          : undefined,
    analysis: { phases } as unknown as SolveMetrics,
  };
}
