"use client";

/**
 * Data layer for the Reconstructions explorer.
 *
 * Assets live in `public/recon-data/` (generated by
 * `pruebas/scripts/build-recon-web-data.ts` from the CubeRoot + reco.nz
 * crawls):
 *   - index.json               → list metadata for every solve
 *   - data/chunk-XXX.json      → full records (scramble, phases, text, stats)
 *
 * Both are fetched lazily and cached in module scope.
 */
import type { Solve } from "@/types";
import type {
  CubeMoveEvent,
  OrientationTimeline,
  SolveMetrics,
} from "@cubalyze/types";
import {
  analyzeSolveText,
  type AnalyzeSolveTextResult,
} from "@cubalyze/analysis-engine";
import {
  conjugatePhaseStream,
  OrientationTable,
  tokenize,
} from "@cubalyze/math-core";

/**
 * Recon dataset puzzle label → canonical WCA event code (ADR-002), so the
 * 3D replay knows which puzzle a record is: "222"/"333" render a real cube,
 * everything else (pyraminx, skewb, square-1, clock, megaminx, 4×4–7×7) has
 * no renderer and shows the "not renderable" placeholder instead of a
 * misleading 3×3 cube.
 */
const RECON_PUZZLE_TO_WCA: Record<string, string> = {
  "2x2": "222",
  "3x3": "333",
  "4x4": "444",
  "5x5": "555",
  "6x6": "666",
  "7x7": "777",
  pyraminx: "pyram",
  skewb: "skewb",
  "square-1": "sq1",
  clock: "clock",
  megaminx: "minx",
};

// ─── Types (mirror of the build script output) ──────────────────────────────

export type ReconSource = "cuberoot" | "reconz";
export type ReconMethodGroup = "CFOP" | "Roux" | "Other";

export interface ReconIndexEntry {
  key: string;
  source: ReconSource;
  id: number;
  solver: string;
  time: number; // seconds
  date: string | null;
  competition: string;
  method: string;
  methodGroup: ReconMethodGroup;
  /** Normalized puzzle label ("3x3", "2x2", "pyraminx", …). */
  puzzle: string;
  stm: number | null;
  tps: number | null;
  tags: string[];
  url: string | null;
}

export interface ReconPhase {
  label: string;
  /** Display notation — a DIRECT parse of the raw phase (wide moves, slices
   *  and rotations keep their written form, e.g. `r'`, `x'`). This is what
   *  the Steps table shows, exactly like the reconstructor wrote it. */
  moves: string;
  /** Raw token count of the display notation (each written move = 1). */
  moveCount: number;
  /** CONJUGATED cube-frame moves for the 3D replay (rotations folded into
   *  the letters): one event per WRITTEN token — a wide's two conjugated
   *  halves (face + slice) MERGE into one two-layer event (`wide: true`),
   *  standalone slices stay single middle-layer turns. Computed at load by
   *  `normalizeReconMoves`; absent in baked data. */
  replayMoves?: string;
  /** Length of `replayMoves` — matches the replay event array 1:1. */
  replayMoveCount?: number;
  /** Per-event `true` when the reconstruction wrote a WIDE move (r/l/u/d/f/b)
   *  for that replay event. Parallel to the `replayMoves` tokens; the engine
   *  rotates the outer AND middle layer together for those. Absent in baked
   *  data (computed at load). */
  replayWide?: boolean[];
  /** Per-event display override — the raw WRITTEN token (e.g. "r'", "U2'",
   *  a remapped "F") for every event, so the UI never shows the conjugated
   *  letter. Parallel to `replayMoves`. Absent in baked data. */
  replayDisplay?: (string | null)[];
}

export interface ReconFullRecord extends ReconIndexEntry {
  scramble: string;
  text: string;
  phases: ReconPhase[];
  /** Reconstructor credits (reco.nz: Brest/Stewy/…, CubeRoot: reconer). */
  reconstructor?: string | null;
  /** Single-solve record tag (WR/NR/PR…) when the source reports one. */
  record?: string | null;
  /** CubeRoot: round average for the solve (seconds). */
  average?: number | null;
  /** CubeRoot: solve number within the round (1..5). */
  solveNum?: number | null;
  /** CubeRoot: cube model used. */
  cube?: string | null;
  /** CubeRoot: ISO country code. */
  country?: string | null;
  /** CubeRoot: official flag ("wca"…). */
  official?: string | null;
  /** CubeRoot: WCA competition id. */
  compWcaId?: string | null;
  stats: {
    crossStm?: number | null;
    f2l?: number | null;
    ll?: number | null;
    yRot?: number | null;
    regrip?: number | null;
    freePair?: number | null;
    sMove?: number | null;
    crossColor?: string | null;
    videoUrl?: string | null;
    recordAverage?: string | null;
  };
  recognition: {
    finalSolved: boolean;
    inspection: string;
    crossVerified: boolean;
  };
  /** Whole-cube rotations (x/y/z) in the stream, computed at load — they
   *  animate the 3D cube's root (the solver's grip) and never count as
   *  replay moves (same as the smartcube path). */
  rotationCount: number;
  /**
   * Computed at load by `normalizeReconMoves` — the CFOP reconstruction
   * (scramble + text through our pipeline) for CFOP 3×3 records. `null` when
   * the analysis failed (the detection panel surfaces that), `undefined` when
   * the record is not CFOP 3×3. Shared with OurDetectionPanel so the stat
   * chips and the detection table always come from ONE analysis run.
   */
  ourDetection?: AnalyzeSolveTextResult | null;
  /** Synthetic orientation keyframes ([eventIndex, orientationIndex]) so the
   *  3D replay rotates the cube to the solver's perspective like the
   *  smartcube path (empty when the record has no rotations).
   *
   *  UNCOMPRESSED: every rotation token emits its own keyframe (the
   *  inspection "z y2" yields TWO keyframes at event 0), so the replay
   *  animates the rotations ONE AFTER ANOTHER instead of one diagonal SLERP.
   *
   *  IMPORTANT: indices are in EVENT space — the same space as the replay
   *  `moves` array (one event per written token, wides merged). Do NOT index
   *  this against the face-only display moves of `p.moves`. */
  orientationTimeline: OrientationTimeline;
}

interface ReconIndexFile {
  version: number;
  count: number;
  chunkSize: number;
  solves: ReconIndexEntry[];
}

// ─── Fetch + cache ──────────────────────────────────────────────────────────

let indexPromise: Promise<ReconIndexFile> | null = null;
const recordCache = new Map<string, Promise<ReconFullRecord | null>>();

function loadIndex(): Promise<ReconIndexFile> {
  indexPromise ??= fetch(`${import.meta.env.BASE_URL}recon-data/index.json`).then(
    (r) => {
      if (!r.ok) throw new Error(`reconstructions index: HTTP ${r.status}`);
      return r.json() as Promise<ReconIndexFile>;
    },
  );
  return indexPromise;
}

/** All list entries (memoised). Throws on fetch failure. */
export function fetchReconIndex(): Promise<ReconIndexEntry[]> {
  return loadIndex().then((f) => f.solves);
}

/** Load the full record for one reconstruction key (cached). */
export function fetchReconRecord(key: string): Promise<ReconFullRecord | null> {
  const cached = recordCache.get(key);
  if (cached) return cached;

  const promise = (async () => {
    const index = await loadIndex();
    const rank = index.solves.findIndex((e) => e.key === key);
    if (rank < 0) return null;
    const chunk = Math.floor(rank / index.chunkSize);
    const file = `${import.meta.env.BASE_URL}recon-data/data/chunk-${String(chunk).padStart(3, "0")}.json`;
    const res = await fetch(file);
    if (!res.ok) throw new Error(`reconstructions chunk ${chunk}: HTTP ${res.status}`);
    const data = (await res.json()) as { solves: ReconFullRecord[] };
    const record = data.solves.find((s) => s.key === key) ?? null;
    if (record) normalizeReconMoves(record);
    return record;
  })();

  recordCache.set(key, promise);
  return promise;
}

// ─── Replay helper ──────────────────────────────────────────────────────────

/**
 * Suffix-aware move forms — CubeRoot writes `U2'` and `R2'` (three chars),
 * which `expandWideMoves` normalizes to `U2`/`R2` before conjugation. Every
 * regex here accepts the `2'` form so RAW display tokens and their expanded
 * counterparts count identically as face turns.
 */
const SUFFIX = "(?:2'|2|')?";

/** Valid outer-face turns — the tokens `conjugatePhaseStream` counts when
 *  emitting orientation keyframes (mirror of its `isSliceToken`). */
const FACE_MOVE_RE = new RegExp(`^[URFDLB]${SUFFIX}$`);

/** Valid animatable moves — outer faces PLUS slices plus lowercase wides.
 *  The 3D engine animates M/E/S as middle-layer turns (FACE_ROTATION_MAP)
 *  and lowercase wides as two-layer turns. */
const ANIMATABLE_MOVE_RE = new RegExp(`^[URFDLBMESrludfb]${SUFFIX}$`);

/** Wide moves as written by the solver (r, l', u2, Rw, Uw2, …). A wide is a
 *  SINGLE replay event that rotates the outer layer AND the middle layer
 *  together; the display keeps the written token verbatim. */
const WIDE_MOVE_RE = new RegExp(`^([rludfb]${SUFFIX}|[RLUDFB]w${SUFFIX})$`);

/**
 * The orientation entry for a DISPLAY token, or null.
 *
 * `tokenize`'s wide-expansion pass normalizes `2'` → `2` (faces AND
 * rotations), so a written `y2'` becomes the rotation `y2` in the expanded /
 * conjugated stream (`perPhase`). The display walk keeps the raw `y2'` — this
 * helper mirrors the normalization so rotation detection aligns 1:1 with the
 * perPhase tokens (a missing step would misalign every subsequent event).
 */
function displayRotationEntry(dt: string) {
  const norm =
    dt.length >= 3 && dt.endsWith("'") && dt[dt.length - 2] === "2"
      ? dt.slice(0, -1)
      : dt;
  return OrientationTable.rotationEntryFor(norm);
}

/**
 * Re-index the synthetic orientation timeline from FACE-move space to RAW
 * EVENT space. `conjugatePhaseStream` counts only outer-face turns (their
 * `isSliceToken` counter) when emitting keyframes — a written wide `r'`
 * counts as ONE face turn (its expanded face half), a slice `M'` counts as
 * ZERO. In the raw replay the event array holds every written token except
 * rotations (wides stay whole), so the mapping is:
 *
 *   face turn k → the raw event index of the k-th face-or-wide token
 *
 * Slices and wides therefore never cause an off-by-N drift between the
 * timeline's face space and the replay's event space.
 */
function reindexTimelineToRawEventSpace(
  timeline: OrientationTimeline,
  displayTokensPerPhase: string[][],
): OrientationTimeline {
  if (timeline.length === 0) return timeline;
  const faceToEvent: number[] = [];
  let faceIdx = 0;
  let eventIdx = 0;
  for (const phase of displayTokensPerPhase) {
    for (const tok of phase) {
      if (displayRotationEntry(tok)) continue;
      // A wide's outer layer IS the counted face turn; a slice is not.
      if (WIDE_MOVE_RE.test(tok) || FACE_MOVE_RE.test(tok)) faceToEvent[faceIdx++] = eventIdx;
      eventIdx++;
    }
  }
  return timeline.map(([moveIndex, orient]) => [
    faceToEvent[moveIndex] ?? moveIndex,
    orient,
  ]);
}

/**
 * Pyraminx-specific normalization — the cube conjugation pipeline would
 * CORRUPT pyraminx notation: the cube tokenizer expands lowercase tips as
 * cube wides (l → "L M", r' → "R' M") and `conjugatePhaseStream` re-cases
 * them, so a perfectly valid scramble "… R l r" becomes "… R L M R M'" —
 * which the Pyraminx engine rejects (M is not a pyraminx move) and the
 * replay silently starts from SOLVED. Pyraminx tokens are single-step WCA
 * moves (U/L/R/B + u/l/r/b, optionally primed) — carry them verbatim.
 */
function normalizePyraminxRecord(record: ReconFullRecord): void {
  record.phases.forEach((p) => {
    const displayTokens = tokenize(p.moves, { expandWide: false });
    p.moves = displayTokens.join(" ");
    p.moveCount = displayTokens.length;
    // Replay tokens: the clean single-step WCA tokens, verbatim (tips keep
    // their lowercase — the replay engine reads displayNotation exactly).
    const clean = displayTokens.filter((t) => PYRAMINX_MOVE_RE.test(t));
    p.replayMoves = clean.join(" ");
    p.replayMoveCount = clean.length;
    p.replayWide = clean.map(() => false);
    p.replayDisplay = clean.map((t) => t);
  });
  // Pyraminx has no cube-frame orientation timeline (no fixed centers /
  // grip rotations in the replay — the vertex axes are the only frame).
  record.rotationCount = 0;
  record.orientationTimeline = [];
  // Keep the scramble verbatim too: never run it through the cube tokenizer
  // (which would expand the trailing tip tokens into invalid M/E moves).
  record.scramble = tokenize(record.scramble, { expandWide: false })
    .filter((t) => PYRAMINX_MOVE_RE.test(t))
    .join(" ");

  deriveReconStats(record);
}

/**
 * Normalize a record's phase moves at load time, once.
 *
 * TWO representations are kept apart:
 *
 * 1. **Display (`p.moves` / `p.moveCount`)** — a DIRECT parse of the raw
 *    phase: `tokenize(..., { expandWide: false })` splits CubeRoot's glued
 *    tokens ("U'D" → U' + D), Unicode primes and the ↓ ↑ · . separators, but
 *    keeps wide moves (`r'`) and rotations (`x'`) as written. The Steps
 *    table shows exactly what the reconstructor wrote.
 * 2. **Replay (`p.replayMoves` / `p.replayMoveCount`)** — the SAME written
 *    tokens minus rotations, one event per token (wides stay whole — the 3D
 *    engine rotates outer + middle layer TOGETHER). These are SOLVER-frame
 *    moves: the 3D replay rotates the cube root to the solver's grip
 *    (inspection + mid-solve rotations from `orientationTimeline`) while the
 *    moves play in the cube's own frame — exactly like the smartcube path,
 *    so the cube ends solved in the solver's perspective.
 *
 * `conjugatePhaseStream` is still used to derive the rotation count and the
 * synthetic orientation timeline (its conjugated stream itself is NOT used
 * for replay anymore — the root rotation replaces conjugation visually).
 *
 * The raw `text` is left untouched for copy.
 */
function normalizeReconMoves(record: ReconFullRecord): void {
  // Pyraminx records skip the whole cube pipeline (see normalizePyraminxRecord
  // above — the cube tokenizer/conjugator would corrupt their tips).
  if (RECON_PUZZLE_TO_WCA[record.puzzle] === "pyram") {
    normalizePyraminxRecord(record);
    return;
  }
  // Conjugated base-frame stream per phase (rotations folded in; wides
  // expanded by tokenize before conjugation). The ENGINE consumes this; the
  // raw tokens only drive display + the orientation timeline.
  const { rotationCount, perPhase } = conjugatePhaseStream(
    record.phases.map((p) => tokenize(p.moves)),
  );
  record.rotationCount = rotationCount;

  const displayTokensPerPhase: string[][] = [];
  // UNCOMPRESSED grip timeline: one keyframe per rotation token, threaded
  // across phases exactly like conjugatePhaseStream's grip (the new rotation
  // composes FIRST).
  const rawOrientTimeline: [number, number][] = [];
  let grip = OrientationTable.IDENTITY;
  let faceIdx = 0;

  record.phases.forEach((p, phaseIdx) => {
    // Display: direct parse of the raw phase — no wide expansion, so the
    // written notation (r', U2', x') survives for the Steps table.
    const displayTokens = tokenize(p.moves, { expandWide: false });
    p.moves = displayTokens.join(" ");
    p.moveCount = displayTokens.length;

    // Grip timeline from the WRITTEN rotation tokens: each rotation emits a
    // keyframe at the number of face turns seen SO FAR (a rotation between
    // moves i and i+1 grips from move i+1; the inspection sits at move 0).
    for (const dt of displayTokens) {
      const rot = displayRotationEntry(dt);
      if (rot) {
        grip = OrientationTable.compose(rot, grip);
        rawOrientTimeline.push([faceIdx, grip.id]);
        continue;
      }
      if (WIDE_MOVE_RE.test(dt) || FACE_MOVE_RE.test(dt)) faceIdx++;
    }

    // ENGINE events: one per WRITTEN token, in the CONJUGATED base frame —
    // so scramble + replayMoves ends solved. A wide's two conjugated halves
    // (face + slice) merge into ONE two-layer event (the engine rotates
    // outer + middle together); standalone slices stay middle-layer turns;
    // rotations live on the orientation timeline (0 events).
    const conj = perPhase[phaseIdx] ?? [];
    const events: { token: string; wide: boolean; display: string | null }[] = [];
    let ci = 0;
    for (const dt of displayTokens) {
      if (displayRotationEntry(dt)) continue; // grip rotation → orientation keyframe
      const isWide = WIDE_MOVE_RE.test(dt);
      if (isWide) {
        const faceTok = conj[ci];
        const sliceTok = conj[ci + 1];
        ci += 2;
        if (
          faceTok && sliceTok &&
          ANIMATABLE_MOVE_RE.test(faceTok) &&
          ANIMATABLE_MOVE_RE.test(sliceTok)
        ) {
          // Merged two-layer event — the display keeps the written token.
          events.push({ token: faceTok, wide: true, display: dt });
          continue;
        }
        // Defensive fallback: emit the halves separately. Never reached for
        // valid streams — conjugation of an expanded wide is 1:1 — so log it
        // loudly instead of silently misaligning the replay.
        console.warn(
          "[reconData] unmergeable conjugated wide",
          record.key,
          p.label,
          dt,
        );
        if (faceTok) events.push({ token: faceTok, wide: false, display: dt });
        if (sliceTok) events.push({ token: sliceTok, wide: false, display: null });
        continue;
      }
      // Non-wide: the conjugated letter drives the engine; the raw WRITTEN
      // token drives the UI (a solver "F" may be a base-frame "U").
      events.push({ token: conj[ci] ?? dt, wide: false, display: dt });
      ci++;
    }
    // Any unconsumed conjugated tokens — should never happen (validated 1:1
    // against every baked record); log it loudly instead of masking a future
    // tokenizer/conjugation regression.
    for (; ci < conj.length; ci++) {
      console.warn(
        "[reconData] unconsumed conjugated tokens",
        record.key,
        p.label,
        conj.slice(ci),
      );
      events.push({ token: conj[ci], wide: false, display: null });
    }

    displayTokensPerPhase.push(displayTokens);
    p.replayMoves = events.map((e) => e.token).join(" ");
    p.replayMoveCount = events.length;
    p.replayWide = events.map((e) => e.wide);
    p.replayDisplay = events.map((e) => e.display);
  });

  // The grip timeline is emitted in FACE-move space; re-index every keyframe
  // to raw-event space so the 3D replay grips the solver's frame at the
  // right event (inspection → keyframe at event 0).
  record.orientationTimeline = reindexTimelineToRawEventSpace(
    rawOrientTimeline,
    displayTokensPerPhase,
  );
  // Scrambles can carry CubeRoot separators too ("↓F2") — tokenize them so
  // the ReplayEngine's applyInitialScramble gets clean elementary tokens.
  record.scramble = tokenize(record.scramble)
    .filter((t) => ANIMATABLE_MOVE_RE.test(t))
    .join(" ");

  deriveReconStats(record);
}

/**
 * Derive the stat chips from the record's own moves so the UI never depends
 * on the baked crawl fields (which are null for most records — e.g. TPS is
 * missing on ~89% of the dataset). Fills ONLY when missing, keeping the
 * source-reported values authoritative where they exist:
 *
 *   - STM: every non-rotation turn token (slice/wide moves count as one,
 *     matching the source sites' slice-turn metric — verified against the
 *     baked values, 97.4% agreement).
 *   - TPS: STM / time (seconds) — the same relation the sources use.
 *   - Cross STM / F2L / LL: from our own CFOP reconstruction (state-based),
 *     only for CFOP 3×3 records (Roux/Other have no CFOP phase meaning).
 */
function deriveReconStats(record: ReconFullRecord): void {
  if (record.stm == null) {
    let stm = 0;
    for (const p of record.phases) {
      // displayRotationEntry normalizes the `2'` suffix before classifying,
      // so rotations written "y2'" are never counted as moves.
      for (const t of tokenize(p.moves, { expandWide: false })) {
        if (!displayRotationEntry(t)) stm++;
      }
    }
    record.stm = stm;
  }
  if (record.tps == null && record.stm != null && record.time > 0) {
    record.tps = record.stm / record.time;
  }

  if (record.methodGroup !== "CFOP" || record.puzzle !== "3x3") return;

  // ONE analysis run feeds both the stat chips and OurDetectionPanel.
  let result: AnalyzeSolveTextResult | null = null;
  try {
    result = analyzeSolveText({
      setup: record.scramble,
      inspection: record.recognition.inspection || undefined,
      solution: record.text,
      method: "CFOP",
      // relaxed cross (permutation-only) matches how reconstructionists mark
      // the cross on text solves — validated by divergence-study (74 fixes,
      // 0 regressions on 300 labelled solves; the written-cross tiebreak
      // `preferredCrossIdx` is what makes it safe). The smart-cube route
      // (no written segments) stays on the strict default.
      relaxedCross: true,
      totalTimeMs: record.time > 0 ? record.time * 1000 : undefined,
    });
  } catch {
    result = null; // the detection panel surfaces the failure — chips stay "—"
  }
  record.ourDetection = result;
  if (!result) return;

  const recon = result.reconstruction;
  const crossStm = recon.cross.moves.length;
  const f2l = recon.pairs.reduce((s, p) => s + p.moves.length, 0);
  const ll = (recon.oll?.moves.length ?? 0) + (recon.pll?.moves.length ?? 0);
  record.stats.crossStm ??= crossStm;
  record.stats.f2l ??= f2l;
  record.stats.ll ??= ll;
}

/**
 * Turn a RAW solver-frame notation string into CubeMoveEvents for the
 * ReplayEngine. The tokens are the solver's own letters (wide moves kept
 * whole — NOT conjugated): the 3D replay rotates the cube root to the
 * solver's grip (orientation timeline) while the moves play in the cube's
 * own frame, exactly like the smartcube path.
 *
 * `options.wide`/`options.display` (parallel to the tokens) mark which
 * events were WIDE moves as written: those get `wide: true` (the engine
 * rotates outer + middle layer TOGETHER) and a `displayNotation` override so
 * the UI shows "r'" instead of "R".
 *
 * Normalizations applied here (display tokens keep the written form for the
 * Steps table, events need the animatable form):
 *   - `U2'` / `R2'` → direction 2 (a 180° turn, `2'` ≡ `2`);
 *   - lowercase wides `r'` → face `R` + `wide: true` (FACE_ROTATION_MAP is
 *     keyed by uppercase faces; the wide flag restores the written token).
 *
 * Events are spaced at a fixed 550ms so the replay timeline is proportional
 * to moves.
 */
/**
 * Pyraminx tokens — single-step WCA moves: layer turns U/L/R/B and tips
 * u/l/r/b, each optionally primed. No 180° moves exist on a Pyraminx.
 */
const PYRAMINX_MOVE_RE = /^[ULRBulrb]'?$/;

/**
 * Turn a Pyraminx reconstruction's notation into the replay event array.
 *
 * The cube's {@link notationToReplayMoves} cannot be reused: it treats
 * lowercase letters as CUBE wides and re-cases them, which would corrupt
 * pyraminx tip turns (a `u` tip is NOT a wide U). Each pyraminx token is
 * therefore carried verbatim in `displayNotation` (the replay engine reads
 * exactly that) — `face`/`direction` are inert carriers for the shared
 * `CubeMoveEvent` shape.
 */
export function pyraminxNotationToReplayMoves(notation: string): CubeMoveEvent[] {
  const tokens = tokenize(notation, { expandWide: false });
  const events: CubeMoveEvent[] = [];
  let ts = 0;
  for (const token of tokens) {
    if (!PYRAMINX_MOVE_RE.test(token)) continue; // rotations / garbage can't play
    events.push({
      face: "U",
      direction: 1,
      displayNotation: token,
      cubeTimestamp: ts,
      hostTimestamp: ts,
    });
    ts += 550;
  }
  return events;
}

export function notationToReplayMoves(
  notation: string,
  options?: { wide?: boolean[]; display?: (string | null)[]; start?: number },
): CubeMoveEvent[] {
  const tokens = tokenize(notation, { expandWide: false });
  const events: CubeMoveEvent[] = [];
  let ts = options?.start ?? 0;
  const wide = options?.wide;
  const display = options?.display;
  for (let i = 0; i < tokens.length; i++) {
    const token = tokens[i];
    if (!ANIMATABLE_MOVE_RE.test(token)) continue; // garbage can't animate
    const isWide = wide?.[i] === true;
    // Wides come in two written forms: lowercase (r') or uppercase with a
    // `w` suffix (Rw', Rw2). The engine's FACE_ROTATION_MAP is keyed by the
    // uppercase FACE letter — normalize while keeping the wide flag + token.
    const face = (isWide ? token[0].toUpperCase() : token[0]) as CubeMoveEvent["face"];
    let suffix = token.slice(1);
    // Uppercase-wide form carries its `w` in the suffix (Rw' → w', Rw2 → w2).
    if (isWide && /^[A-Z]/.test(token[0]) && suffix.startsWith("w")) {
      suffix = suffix.slice(1);
    }
    suffix = suffix === "2'" ? "2" : suffix; // U2' ≡ U2
    const direction = suffix === "2" ? 2 : suffix === "'" ? -1 : 1;
    events.push({
      face,
      direction,
      wide: isWide,
      // Reconstruction solves carry the raw WRITTEN token for EVERY event
      // (a solver "F" may be a base-frame "U" after conjugation) — the UI
      // shows the writer's notation, never the conjugated letter. Smart-cube
      // solves pass no display array (fall back to the face token).
      displayNotation: display?.[i] ?? (isWide ? face + suffix : undefined),
      cubeTimestamp: ts,
      hostTimestamp: ts,
    });
    ts += 550;
  }
  return events;
}

/**
 * Adapt a reconstruction record to the `Solve` shape the ReplaySection
 * consumes (replay canvas + transport + live phase indicator).
 */
export function reconToSolve(record: ReconFullRecord): Solve {
  // Replay path uses the CONJUGATED cube-frame moves (replayMoves): the
  // engine applies them in the cube's own frame so scramble + replayMoves
  // ends SOLVED, while the `orientationTimeline` rotates the cube root to
  // the solver's grip — inspection pre-roll before move 1, mid-solve
  // keyframes — so the cube follows the solver's perspective (like the
  // smartcube path). Wide marks + raw display overrides travel alongside so
  // a written `r'` replays as ONE two-layer move showing "r'".
  const allTokens: string[] = [];
  const allWide: boolean[] = [];
  const allDisplay: (string | null)[] = [];
  for (const p of record.phases) {
    const tokens = (p.replayMoves ?? p.moves).split(" ").filter(Boolean);
    allTokens.push(...tokens);
    allWide.push(...(p.replayWide ?? tokens.map(() => false)));
    allDisplay.push(...(p.replayDisplay ?? tokens.map(() => null)));
  }
  const isPyraminx = RECON_PUZZLE_TO_WCA[record.puzzle] === "pyram";
  // Pyraminx records replay on their own engine with verbatim WCA tokens;
  // cube records use the conjugated-frame converter.
  const moves = isPyraminx
    ? pyraminxNotationToReplayMoves(allTokens.join(" "))
    : notationToReplayMoves(allTokens.join(" "), {
        wide: allWide,
        display: allDisplay,
      });

  // The synthetic orientation timeline rotates the 3D cube's root to the
  // solver's perspective during replay (inspection pre-roll + mid-solve
  // keyframes). Passed to the engine ALWAYS (conjugated moves + grip is what
  // makes the cube BOTH solve and follow the solver's frame).
  const orientationTimeline =
    record.orientationTimeline && record.orientationTimeline.length > 0
      ? record.orientationTimeline
      : undefined;

  // p.replayMoveCount matches the replay `moves` array below exactly (one
  // event per written token, rotations never counted, wides merged).
  const phases: SolveMetrics["phases"] = record.phases.map((p) => ({
    phaseName: p.label,
    durationMs: 0,
    moveCount: p.replayMoveCount ?? p.moveCount,
    tps: 0,
    pauseCount: 0,
    pauseTimeMs: 0,
  }));

  const dateTs = record.date ? Date.parse(record.date) : 0;

  return {
    id: record.key,
    time: Math.round(record.time * 1000),
    penalty: "none",
    scramble: record.scramble,
    timestamp: Number.isFinite(dateTs) ? dateTs : 0,
    method: record.method as Solve["method"],
    source: "manual",
    moves,
    orientationTimeline,
    // `replayMovesConjugated: true` — the moves ARE base-frame conjugated
    // letters. The replay section rotates the cube root by the orientation
    // timeline (the solver's grip: inspection pre-roll + mid-solve keyframes)
    // so the cube solves AND follows the solver's perspective, and the
    // per-event display overrides show the raw written notation.
    replayMovesConjugated: true,
    // Canonical WCA code (ADR-002) — 2×2 replays on a 2×2 cube, 3×3 on a
    // 3×3; non-cube puzzles (pyraminx, skewb, …) resolve to "no renderer"
    // in ReplaySection instead of silently falling back to a 3×3.
    puzzleType: RECON_PUZZLE_TO_WCA[record.puzzle],
    analysis: { phases } as unknown as SolveMetrics,
  };
}
