export enum TimerState {
  IDLE = 'IDLE',
  INSPECTION = 'INSPECTION',
  READY_FOR_MOVE = 'READY_FOR_MOVE',
  TOUCHING = 'TOUCHING',
  READY = 'READY',
  RUNNING = 'RUNNING',
  STOPPED = 'STOPPED',
  COOLDOWN = 'COOLDOWN'
}
