export enum TimerState {
  IDLE = 'IDLE',
  INSPECTION = 'INSPECTION',
  ARMED = 'ARMED',
  TOUCHING = 'TOUCHING',
  READY = 'READY',
  RUNNING = 'RUNNING',
  STOPPED = 'STOPPED',
  COOLDOWN = 'COOLDOWN'
}
