/**
 * Test: the JSON generated by pruebas/scripts/scdb_parser.py is the source of
 * truth for the seeds — the seed files are regenerated from it (via
 * pruebas/scripts/generate_seed_catalog.py), keeping only the caseDefs of the
 * previous hand-curated seed. Therefore every algorithm in the seed MUST exist
 * in the generated JSON (strict superset, no tolerated variants), and the
 * default algorithm of each seed case must match the JSON default (the SCDB
 * "Standard Alg").
 *
 * The test skips itself if the JSON files are missing (pruebas/ is gitignored).
 *
 * Run: npx vitest run packages/algorithm-db/src/__tests__/scdb-import-comparison.test.ts
 */

import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "fs";
import { resolve } from "path";
import { getSeedData } from "../seed/index";

interface GeneratedAlg { moves: string[]; isDefault: boolean; votes?: number; notes?: string | null }
interface GeneratedCase { caseDef: { caseNumber: string; subsetId: string }; algorithms: GeneratedAlg[] }
interface GeneratedFile { source: string; set: string; subsetId: string; cases: GeneratedCase[] }

const GENERATED: Record<string, string> = {
  pll: resolve(__dirname, "../../../../pruebas/generated/scdb-pll.json"),
  oll: resolve(__dirname, "../../../../pruebas/generated/scdb-oll.json"),
  // AdvancedF2L is seeded from the FUSED dump (fase5-fuse.ts: SCDB+BirdF2L+Quest).
  af2l: resolve(__dirname, "../../../../pruebas/generated/scdb-af2l-fused.json"),
};

const SUBSET_IDS = {
  pll: "00000000-0000-4000-9000-000000000001",
  oll: "00000000-0000-4000-9000-000000000002",
  af2l: "00000000-0000-4000-9000-000000000004",
};

function loadGenerated(key: string): GeneratedFile | null {
  const path = GENERATED[key];
  if (!existsSync(path)) return null;
  return JSON.parse(readFileSync(path, "utf-8")) as GeneratedFile;
}

const hasAll = Object.values(GENERATED).every((p) => existsSync(p));

/**
 * Collapses consecutive moves of the same face and direction (`R' R'` → `R2`).
 * SCDB writes trigger groups un-simplified while the seeds store `R2`.
 */
function collapseConsecutive(moves: string[]): string[] {
  const out: string[] = [];
  for (const m of moves) {
    const prev = out[out.length - 1];
    if (prev !== undefined) {
      const b1 = prev.replace(/2[']/, "");
      const b2 = m.replace(/2[']/, "");
      const d1 = prev.includes("2");
      const d2 = m.includes("2");
      if (b1 === b2 && !d1 && !d2 && prev.endsWith("'") === m.endsWith("'")) {
        out.pop();
        out.push(`${b1}2`);
        continue;
      }
    }
    out.push(m);
  }
  return out;
}

/** Compares two algs ignoring consecutive-double simplification. */
function movesEqual(a: string[] | undefined, b: string[] | undefined): boolean {
  return JSON.stringify(collapseConsecutive(a ?? [])) === JSON.stringify(collapseConsecutive(b ?? []));
}

describe.runIf(hasAll)("SCDB Import (parser) vs seed catalog", () => {
  const seed = getSeedData();

  for (const [key, label, expectedCases] of [
    ["pll", "PLL", 21],
    ["oll", "OLL", 57],
    ["af2l", "AdvancedF2L", 126],
  ] as const) {
    const gen = loadGenerated(key)!;
    const subsetId = SUBSET_IDS[key];
    const seedCases = seed.cases.filter((c) => c.subsetId === subsetId);
    const genByNumber = new Map(gen.cases.map((c) => [c.caseDef.caseNumber, c]));

    describe(label, () => {
      it(`the generated dump has ${expectedCases} cases`, () => {
        expect(gen.cases.length).toBe(expectedCases);
      });

      it(`every ${label} case in the seed exists in the generated JSON`, () => {
        const missing = seedCases.filter((c) => !genByNumber.has(c.caseNumber)).map((c) => c.caseNumber);
        expect(missing).toEqual([]);
      });

      it("each generated case marks exactly 1 default algorithm", () => {
        for (const c of gen.cases) {
          expect(c.algorithms.filter((a) => a.isDefault).length).toBe(1);
        }
      });

      it("strict superset: every seed algorithm exists in the generated JSON", () => {
        const unexpected: string[] = [];
        let seedAlgsChecked = 0;
        for (const sc of seedCases) {
          const gc = genByNumber.get(sc.caseNumber)!;
          const genMoves = new Set(gc.algorithms.map((a) => JSON.stringify(collapseConsecutive(a.moves))));
          for (const a of seed.algorithms.filter((al) => al.caseId === sc.id)) {
            seedAlgsChecked++;
            if (!genMoves.has(JSON.stringify(collapseConsecutive(a.moves)))) {
              unexpected.push(`${sc.caseNumber}: ${a.moves.join(" ")}`);
            }
          }
        }
        console.log(`\n[superset ${label}] ${seedAlgsChecked - unexpected.length}/${seedAlgsChecked} seed algs present in the dump`);
        if (unexpected.length > 0) console.log(`  missing from dump:\n    ${unexpected.join("\n    ")}`);
        expect(unexpected).toEqual([]);
      });

      it("default algorithm of each seed case matches the JSON default (audit)", () => {
        console.log(`\n=== ${label}: seed default vs generated default ===`);
        let match = 0;
        for (const sc of seedCases) {
          const gc = genByNumber.get(sc.caseNumber)!;
          const seedDefault = seed.algorithms.filter((a) => a.caseId === sc.id).find((a) => a.isDefault);
          const genDefault = gc.algorithms.find((a) => a.isDefault)!;
          const same = movesEqual(seedDefault?.moves, genDefault.moves);
          if (same) match++;
          console.log(
            `${sc.caseNumber.padEnd(8)} ${same ? "✓" : "✗"}  ${(seedDefault?.moves ?? []).join(" ")}`,
          );
        }
        expect(match).toBe(seedCases.length);
        console.log(`Exact matches: ${match}/${seedCases.length}`);
      });
    });
  }

  it("AdvancedF2L has algorithms for all 4 slots (FR/FL/BL/BR)", () => {
    const gen = loadGenerated("af2l")!;
    const slotNotes = new Set(gen.cases.flatMap((c) => c.algorithms.map((a) => a.notes)));
    expect(slotNotes.has("Slot: FR")).toBe(true);
    expect(slotNotes.has("Slot: FL")).toBe(true);
    expect(slotNotes.has("Slot: BL")).toBe(true);
    expect(slotNotes.has("Slot: BR")).toBe(true);
  });
});
