/**
 * Nivel 3 — Property-Based Tests (fast-check)
 *
 * Uses fast-check v4 to verify mathematical invariants with
 * deterministic, reproducible random inputs. No Math.random()
 * inside arbitraries — all randomness goes through fast-check
 * so shrinking and seed-reproduction work correctly.
 */
import { describe, it, expect } from 'vitest';
import fc from 'fast-check';
import {
  CubeState,
  Cube2x2State,
  FaceletStringConverter,
  Cube2x2FaceletConverter,
} from '@cubalyze/math-core';
import { Min2PhaseSolver } from '../Min2PhaseSolver';
import { TwoByTwoSolver } from '../TwoByTwoSolver';

// ═══════════════════════════════════════════════════════════════════════
//  Arbitraries — pure fast-check generators (no Math.random!)
// ═══════════════════════════════════════════════════════════════════════

const FACES_3X3 = ['U', 'R', 'F', 'D', 'L', 'B'] as const;
const SUFFIXES = ['', '2', "'"] as const;

/** A single 3×3 move token like "U", "R2", or "F'". */
const arbitraryMove3x3 = fc.tuple(
  fc.constantFrom(...FACES_3X3),
  fc.constantFrom(...SUFFIXES),
).map(([face, suffix]) => `${face}${suffix}`);

/**
 * A valid scramble sequence: array of moves where consecutive moves
 * on the same face are filtered out (no redundant U U2).
 */
const arbitraryScramble3x3 = fc
  .array(arbitraryMove3x3, { minLength: 1, maxLength: 50 })
  .map((moves) => {
    // Filter consecutive same-face moves
    const filtered: string[] = [];
    for (const m of moves) {
      if (filtered.length > 0 && filtered[filtered.length - 1][0] === m[0]) {
        continue; // skip consecutive same-face
      }
      filtered.push(m);
    }
    return filtered;
  });

/** A random valid 3×3 cube state generated by applying a scramble. */
const arbitraryCubeState3x3 = arbitraryScramble3x3.map((moves) => {
  const state = new CubeState();
  if (moves.length > 0) {
    state.applySequence(moves.join(' '));
  }
  return state;
});

// ── 2×2 arbitraries ─────────────────────────────────────────────────

const FACES_2X2 = ['U', 'R', 'F'] as const;

const arbitraryMove2x2 = fc.tuple(
  fc.constantFrom(...FACES_2X2),
  fc.constantFrom(...SUFFIXES),
).map(([face, suffix]) => `${face}${suffix}`);

const arbitraryScramble2x2 = fc
  .array(arbitraryMove2x2, { minLength: 1, maxLength: 30 })
  .map((moves) => {
    const filtered: string[] = [];
    for (const m of moves) {
      if (filtered.length > 0 && filtered[filtered.length - 1][0] === m[0]) {
        continue;
      }
      filtered.push(m);
    }
    return filtered;
  });

/**
 * A random valid 2×2 state where DBL (cp[6]=6, co[6]=0) is fixed.
 * Generates via applying a U,R,F scramble to a solved state,
 * so the DBL corner stays in place by construction.
 */
const arbitraryCube2x2State = arbitraryScramble2x2.map((moves) => {
  const state = new Cube2x2State();
  if (moves.length > 0) {
    state.applySequence(moves.join(' '));
  }
  return state;
});

// ═══════════════════════════════════════════════════════════════════════
//  P1: ∀ 3×3 random state: applySequence(solve(state)) → isSolved
// ═══════════════════════════════════════════════════════════════════════

describe('P1 — 3×3 solve round-trip', { timeout: 120000 }, () => {
  const solver = new Min2PhaseSolver();

  it('∀ random 3×3 state: solve + apply = solved', () => {
    fc.assert(
      fc.property(arbitraryCubeState3x3, (state) => {
        const clone = state.clone();
        const solution = solver.solve(state);

        // Non-empty solution for any non-trivial state
        if (!clone.isSolved()) {
          expect(solution.trim().length).toBeGreaterThan(0);
        }

        clone.applySequence(solution);
        expect(clone.isSolved()).toBe(true);
      }),
      { numRuns: 50, endOnFailure: true },
    );
  });
});

// ═══════════════════════════════════════════════════════════════════════
//  P3: Min2Phase solution bound (≤ 22 — it's near-optimal, not optimal)
// ═══════════════════════════════════════════════════════════════════════

describe('P3 — Min2Phase solution length bound', { timeout: 120000 }, () => {
  const solver = new Min2PhaseSolver();

  it('∀ 3×3 state: solution ≤ 22 moves (2-phase near-optimal)', () => {
    fc.assert(
      fc.property(arbitraryCubeState3x3, (state) => {
        const solution = solver.solve(state);
        const moveCount = solution
          .trim()
          .split(/\s+/)
          .filter((m) => m.length > 0).length;

        if (moveCount > 0) {
          // Min2Phase is a 2-phase solver: solutions are within 1-2 moves
          // of optimal. God's number is 20, so 22 is a safe bound.
          expect(moveCount).toBeLessThanOrEqual(22);
        }
      }),
      { numRuns: 50, endOnFailure: true },
    );
  });
});

// ═══════════════════════════════════════════════════════════════════════
//  P2: ∀ 2×2 random state: solve + applySolution = solved
// ═══════════════════════════════════════════════════════════════════════

describe('P2 — 2×2 solve round-trip', { timeout: 120000 }, () => {
  const solver = new TwoByTwoSolver();
  solver.init();

  it('∀ random 2×2 state: solve + apply = solved', () => {
    fc.assert(
      fc.property(arbitraryCube2x2State, (state) => {
        const clone = state.clone();
        const solution = solver.solve(state);

        // TwoByTwoSolver returns empty string for invalid states
        // (DBL not fixed). All our generated states have DBL fixed.
        if (solution.length === 0 && clone.isSolved()) {
          return; // Already solved, empty solution is correct
        }
        expect(solution.length).toBeGreaterThan(0);

        clone.applySequence(solution);
        expect(clone.isSolved()).toBe(true);
      }),
      { numRuns: 50, endOnFailure: true },
    );
  });
});

// ═══════════════════════════════════════════════════════════════════════
//  P4: ∀ 2×2 state, solution length ≤ 11 (God's Number 2×2)
// ═══════════════════════════════════════════════════════════════════════

describe('P4 — TwoByTwoSolver optimal bound', { timeout: 120000 }, () => {
  const solver = new TwoByTwoSolver();
  solver.init();

  it('∀ 2×2 state: solution ≤ 11 moves (optimal)', () => {
    fc.assert(
      fc.property(arbitraryCube2x2State, (state) => {
        const solution = solver.solve(state);
        const moveCount = solution
          .trim()
          .split(/\s+/)
          .filter((m) => m.length > 0).length;

        if (moveCount > 0) {
          // TwoByTwoSolver is optimal (exact heuristic IDA*). God's number = 11.
          expect(moveCount).toBeLessThanOrEqual(11);
        }
      }),
      { numRuns: 50, endOnFailure: true },
    );
  });
});

// ═══════════════════════════════════════════════════════════════════════
//  P5: ∀ random sequence: invert(seq) + seq = solved
// ═══════════════════════════════════════════════════════════════════════

describe('P5 — invert + apply = solved', () => {
  it('∀ random 3×3 sequence: inverse restores solved', () => {
    fc.assert(
      fc.property(arbitraryScramble3x3, (moves) => {
        if (moves.length === 0) return;

        const seq = moves.join(' ');
        const inverted: string[] = [];
        for (let i = moves.length - 1; i >= 0; i--) {
          const m = moves[i];
          if (m.endsWith("'")) inverted.push(m[0]);
          else if (m.endsWith('2')) inverted.push(m);
          else inverted.push(m + "'");
        }
        const inverse = inverted.join(' ');

        const state = new CubeState();
        state.applySequence(seq);
        state.applySequence(inverse);
        expect(state.isSolved()).toBe(true);
      }),
      { numRuns: 200, endOnFailure: true },
    );
  });

  it('∀ random 2×2 sequence: invert + apply = solved', () => {
    fc.assert(
      fc.property(arbitraryScramble2x2, (moves) => {
        if (moves.length === 0) return;
        const seq = moves.join(' ');

        const inverse = Cube2x2State.invertNotation(seq);
        const state = new Cube2x2State();
        state.applySequence(seq);
        state.applySequence(inverse);
        expect(state.isSolved()).toBe(true);
      }),
      { numRuns: 200, endOnFailure: true },
    );
  });
});

// ═══════════════════════════════════════════════════════════════════════
//  P6: ∀ 2×2 state: Σ corner orientations ≡ 0 (mod 3)
// ═══════════════════════════════════════════════════════════════════════

describe('P6 — 2×2 corner orientation invariant', () => {
  it('∀ random 2×2 state: sum of co is divisible by 3', () => {
    fc.assert(
      fc.property(arbitraryCube2x2State, (state) => {
        let sum = 0;
        for (let i = 0; i < 8; i++) sum += state.co[i];
        expect(sum % 3).toBe(0);
      }),
      { numRuns: 200, endOnFailure: true },
    );
  });

  it('co sum invariant is preserved after applying more U,R,F moves', () => {
    fc.assert(
      fc.property(
        arbitraryCube2x2State,
        arbitraryScramble2x2,
        (state, extraMoves) => {
          const originalSum = Array.from(state.co).reduce((a, v) => a + v, 0) % 3;

          if (extraMoves.length > 0) {
            state.applySequence(extraMoves.join(' '));
          }

          const newSum = Array.from(state.co).reduce((a, v) => a + v, 0) % 3;
          expect(newSum).toBe(originalSum);
        },
      ),
      { numRuns: 100, endOnFailure: true },
    );
  });
});

// ═══════════════════════════════════════════════════════════════════════
//  P7: ∀ 3×3 state: Σ edge orientations ≡ 0 (mod 2)
// ═══════════════════════════════════════════════════════════════════════

describe('P7 — 3×3 edge orientation invariant', () => {
  it('∀ random 3×3 state: eo sum parity is 0', () => {
    fc.assert(
      fc.property(arbitraryCubeState3x3, (state) => {
        let sum = 0;
        for (let i = 0; i < 12; i++) sum += state.eo[i];
        expect(sum % 2).toBe(0);
      }),
      { numRuns: 100, endOnFailure: true },
    );
  });
});

// ═══════════════════════════════════════════════════════════════════════
//  P8: ∀ 3×3 state: parity(cp) ≡ parity(ep)
// ═══════════════════════════════════════════════════════════════════════

describe('P8 — 3×3 permutation parity invariant', () => {
  it('∀ random 3×3 state: corner and edge permutation parity match', () => {
    fc.assert(
      fc.property(arbitraryCubeState3x3, (state) => {
        let cpInversions = 0;
        for (let i = 0; i < 8; i++) {
          for (let j = i + 1; j < 8; j++) {
            if (state.cp[i] > state.cp[j]) cpInversions++;
          }
        }

        let epInversions = 0;
        for (let i = 0; i < 12; i++) {
          for (let j = i + 1; j < 12; j++) {
            if (state.ep[i] > state.ep[j]) epInversions++;
          }
        }

        expect(cpInversions % 2).toBe(epInversions % 2);
      }),
      { numRuns: 100, endOnFailure: true },
    );
  });
});

// ═══════════════════════════════════════════════════════════════════════
//  P9: ∀ solve with moves: TPS = moveCount / (timeMs / 1000) has
//      valid numeric properties (finite, non-negative)
// ═══════════════════════════════════════════════════════════════════════

describe('P9 — TPS numeric stability', () => {
  it('TPS always finite and non-NaN for valid inputs', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 0, max: 200 }),
        fc.integer({ min: 1, max: 600000 }),
        (moveCount, timeMs) => {
          const tps = moveCount / (timeMs / 1000);
          expect(Number.isFinite(tps)).toBe(true);
          expect(Number.isNaN(tps)).toBe(false);
          expect(tps).toBeGreaterThanOrEqual(0);
        },
      ),
      { numRuns: 200, endOnFailure: true },
    );
  });

  it('TPS = 0 when moveCount = 0 regardless of time', () => {
    fc.assert(
      fc.property(fc.integer({ min: 1, max: 600000 }), (timeMs) => {
        const tps = 0 / (timeMs / 1000);
        expect(tps).toBe(0);
      }),
      { numRuns: 50, endOnFailure: true },
    );
  });
});

// ═══════════════════════════════════════════════════════════════════════
//  P10: ∀ valid FaceletString → structural consistency
// ═══════════════════════════════════════════════════════════════════════

describe('P10 — FaceletString structural consistency', () => {
  it('∀ 3×3 state: toFaceletString produces 6×9 = 54 color facelets', () => {
    fc.assert(
      fc.property(arbitraryCubeState3x3, (state) => {
        const facelets = FaceletStringConverter.toFaceletString(state);
        expect(facelets.length).toBe(54);
        expect(facelets).toMatch(/^[URFDLB]{54}$/);

        const counts: Record<string, number> = {};
        for (const c of facelets) counts[c] = (counts[c] || 0) + 1;
        for (const color of ['U', 'R', 'F', 'D', 'L', 'B']) {
          expect(counts[color]).toBe(9);
        }
      }),
      { numRuns: 100, endOnFailure: true },
    );
  });

  it('∀ 2×2 state: toFaceletString produces 6×4 = 24 color facelets', () => {
    fc.assert(
      fc.property(arbitraryCube2x2State, (state) => {
        const facelets = Cube2x2FaceletConverter.toFaceletString(state);
        expect(facelets.length).toBe(24);
        expect(facelets).toMatch(/^[URFDLB]{24}$/);

        const counts: Record<string, number> = {};
        for (const c of facelets) counts[c] = (counts[c] || 0) + 1;
        for (const color of ['U', 'R', 'F', 'D', 'L', 'B']) {
          expect(counts[color]).toBe(4);
        }
      }),
      { numRuns: 100, endOnFailure: true },
    );
  });
});
